# Generated by Django 5.0.1 on 2024-02-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_delivery',
            new_name='is_sales',
        ),
    ]
