# Generated by Django 5.0.1 on 2024-02-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0003_rename_is_delivery_profile_is_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
