# Generated by Django 5.0.1 on 2024-02-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_and_services', '0003_alter_organizations_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_services',
            options={'verbose_name_plural': 'Project Services'},
        ),
    ]
