# Generated by Django 5.0.1 on 2024-02-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_and_services', '0004_alter_project_services_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizations',
            old_name='arabic_name',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='organizations',
            old_name='english_name',
            new_name='contact_name',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organizations',
            name='number_of_branches',
        ),
        migrations.AddField(
            model_name='organizations',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='contact_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organizations',
            name='organization_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
