# Generated by Django 5.0.1 on 2024-02-08 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_and_services', '0005_rename_arabic_name_organizations_contact_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AlterField(
            model_name='project_services',
            name='service_percentage_rate',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='projects',
            name='percentage_rate',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
