# Generated by Django 5.0.1 on 2024-02-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_and_services', '0006_delete_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='project_name',
        ),
    ]
