# Generated by Django 5.0.1 on 2024-02-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_and_services', '0007_rename_name_projects_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='yearly_spendings',
            new_name='total_project_cost',
        ),
    ]
