# Generated by Django 5.0.1 on 2024-02-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations_and_services', '0008_rename_yearly_spendings_projects_total_project_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='quarter_joined',
            new_name='quarter_closed',
        ),
    ]
