# Generated by Django 4.2.7 on 2024-02-08 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations_and_services",
            "0009_rename_quarter_joined_projects_quarter_closed",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=100, null=True)),
                ("files", models.FileField(upload_to="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations_and_services.projects",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Documents",
            },
        ),
    ]
